---
# tasks file for haproxy_keepalived_conf
- name: Install haproxy, keepalived and selinux libs
  ansible.builtin.package:
    name:
      - haproxy
      - keepalived
      - libselinux-python3
      - libsemanage-python3
      - python3-libsemanage
    state: latest

- name: Set haproxy_connect_any on and keep it persistent across reboots
  ansible.posix.seboolean:
    name: haproxy_connect_any
    state: true
    persistent: true

- name: Create haproxy dev dir
  ansible.builtin.file:
    path: /var/lib/haproxy/dev
    group: haproxy
    owner: haproxy
    state: directory
  when: rke2_state == "start"

- name: Verify haproxy rsyslog conf
  stat:
    path: "/etc/rsyslog.d/haproxy.conf"
  register: result_rsyslog_conf

- name: Configure haproxy on rsyslog
  ansible.builtin.copy:
    src: haproxy.conf
    dest: /etc/rsyslog.d/haproxy.conf
  when: not result_rsyslog_conf.stat.exists

- name: Configure HAProxy
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0600'
  when: rke2_state == "start"

- name: Configure keepalived
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  when: rke2_state == "start"

- name: Enable rsyslog
  ansible.builtin.systemd_service:
    name: rsyslog
    state: restarted
    enabled: true
  when: rke2_state == "start"

- name: Enable haproxy
  ansible.builtin.systemd_service:
    name: haproxy
    state: restarted
    enabled: true
  when: rke2_state == "start"

- name: Enable keepalived
  ansible.builtin.systemd_service:
    name: keepalived
    state: restarted
    enabled: true
  when: rke2_state == "start"