- hosts: haproxy_keepalived
  become: yes
  name: Configure HAProxy and Keepalived
  roles:
    - haproxy_keepalived_conf

- hosts: etcd:control_plane:worker_nodes
  become: yes
  name: Configure K8s params
  roles:
    - k8s_params_conf

- hosts: etcd
  become: yes
  name: Configure ETCD Cluster
  roles:
    - etcd_cluster_conf

- hosts: control_plane
  become: yes
  name: Configure Control Plane Cluster
  roles:
    - control_plane_cluster_conf

- hosts: worker_nodes
  become: yes
  name: Configure Worker Nodes
  roles:
    - worker_nodes_conf
    - create_haproxy_serviceaccount_conf

- hosts: haproxy_keepalived
  become: yes
  name: Configure HAProxy Health check to k8s api-server to l7
  roles:
    - change_control_plane_health_check_to_l7_conf