- hosts: haproxy_keepalived
  remote_user: rkeoci
  become: yes
  name: Configure HAProxy and Keepalived
  roles:
    - haproxy_keepalived_conf

- hosts: etcd
  run_once: true
  remote_user: rkeoci
  become: yes
  name: Configure ETCD-0 Node
  roles:
    - etcd_0_conf

- hosts: etcd
  remote_user: rkeoci
  become: yes
  name: Configure ETCD Cluster
  roles:
    - etcd_cluster_conf

- hosts: control_plane
  remote_user: rkeoci
  become: yes
  name: Configure Control Plane Cluster
  roles:
    - control_plane_cluster_conf

- hosts: worker_nodes
  remote_user: rkeoci
  become: yes
  name: Configure Worker Nodes
  roles:
    - worker_nodes_conf

- hosts: worker_nodes
  run_once: true
  remote_user: rkeoci
  become: yes
  name: Configure HAProxy ServiceAccount
  roles:
    - create_haproxy_serviceaccount_conf

- hosts: haproxy_keepalived
  remote_user: rkeoci
  become: yes
  name: Configure HAProxy Health check to k8s api-server to l7
  roles:
    - change_control_plane_health_check_to_l7_conf