---
# tasks file for etcd_cluster_conf
- name: Download RKE2 script
  ansible.builtin.get_url:
    url: https://get.rke2.io
    dest: /tmp/install-rke2.sh
    mode: '0100'

- name: Install RKE2
  ansible.builtin.shell: /tmp/install-rke2.sh
  environment:
    INSTALL_RKE2_TYPE: "server"
    INSTALL_RKE2_VERSION: "{{ rke2_version }}"

- name: Enable rke2-server.service
  ansible.builtin.shell: systemctl enable rke2-server.service

- name: Configure ETCD node
  ansible.builtin.template:
    src: config.yaml.j2
    dest: /etc/rancher/rke2/config.yaml

- name: Create cilium dir
  ansible.builtin.file:
    path: /var/lib/rancher/rke2/server/manifests
    group: root
    owner: root
    state: directory

- name: Configure Cilium Hubble
  ansible.builtin.copy:
    src: rke2-cilium-config.yaml
    dest: /var/lib/rancher/rke2/server/manifests/rke2-cilium-config.yaml

- name: Enable rke-server etcd-0
  ansible.builtin.shell: systemctl {{ rke2_state }} rke2-server.service
  when: inventory_hostname == (groups['etcd'] | first)

- name: Enable rke-server
  ansible.builtin.shell: systemctl {{ rke2_state }} rke2-server.service
  when: not inventory_hostname == (groups['etcd'] | first)

- name: Copy kubeconfig
  ansible.builtin.copy:
    remote_src: true
    src: /etc/rancher/rke2/rke2.yaml
    dest: "/home/{{ ansible_user }}/rke2-kubeconfig"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  when: inventory_hostname == (groups['etcd'] | first)

- name: Validate YQ installation
  stat:
    path: "/tmp/yq"
  register: yq_installation_result
  when: inventory_hostname == (groups['etcd'] | first)

- name: Download YQ
  ansible.builtin.get_url:
    url: https://github.com/mikefarah/yq/releases/download/v4.44.1/yq_linux_amd64
    dest: /tmp/yq
    mode: '0666'
  when: inventory_hostname == (groups['etcd'] | first) and not yq_installation_result.stat.exists

- name: Change kubeconfig server to haproxy vip
  ansible.builtin.shell: |
    chmod +x /tmp/yq
    /tmp/yq e -i '.clusters[0].cluster.server = "https://{{ haproxy_vip }}:6443"' /home/{{ ansible_user }}/rke2-kubeconfig
    /tmp/yq e -i '.clusters[0].name = "{{ rke2_cluster_name }}"' /home/{{ ansible_user }}/rke2-kubeconfig
    /tmp/yq e -i '.contexts[0].context.cluster = "{{ rke2_cluster_name }}"' /home/{{ ansible_user }}/rke2-kubeconfig
    /tmp/yq e -i '.contexts[0].name = "{{ rke2_cluster_name }}"' /home/{{ ansible_user }}/rke2-kubeconfig
    /tmp/yq e -i '.current-context = "{{ rke2_cluster_name }}"' /home/{{ ansible_user }}/rke2-kubeconfig
  when: inventory_hostname == (groups['etcd'] | first)

- name: Fetch kubeconfig
  ansible.builtin.fetch:
    src: "/home/{{ ansible_user }}/rke2-kubeconfig"
    dest: rke2-kubeconfig
  when: inventory_hostname == (groups['etcd'] | first)