---
# tasks file for k8s_params_conf
- name: Disable swap
  ansible.builtin.shell: swapoff -a

- name: Comment out swap entries in /etc/fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$' # Matches lines containing 'swap sw' not already commented
    replace: '# \1' # Comments out the matched line
    backup: yes # Creates a backup of the original /etc/fstab

- name: Disable dnf-makecache.timer
  ansible.builtin.shell: systemctl disable --now dnf-makecache.timer

- name: Creating k8s-conf modules-load file
  copy:
    dest: "/etc/modules-load.d/k8s.conf"
    content: |
      br_netfilter
      ip_vs_rr
      ip_vs_wrr
      ip_vs_sh
      nf_conntrack_ipv4
      ip_vs

- name: Create Sysctl K8s Conf file
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1

- name: Modprobe overlay
  community.general.modprobe:
    name: overlay

- name: Modprobe br_netfilter
  community.general.modprobe:
    name: br_netfilter

- name: Modeprobe nf_nat
  community.general.modprobe:
    name: nf_nat

- name: Modeprobe xt_REDIRECT
  community.general.modprobe:
    name: xt_REDIRECT

- name: Modeprobe xt_owner
  community.general.modprobe:
    name: xt_owner

- name: Modeprobe iptable_nat
  community.general.modprobe:
    name: iptable_nat

- name: Modeprobe iptable_mangle
  community.general.modprobe:
    name: iptable_mangle

- name: Modeprobe iptable_filter
  community.general.modprobe:
    name: iptable_filter

- name: Set max_user_watches
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    line: 'fs.inotify.max_user_watches={{ max_user_watches }}'
    regexp: '^fs\.inotify\.max_user_watches={{ max_user_watches }}'
    state: present

- name: Set max_user_instances
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    line: 'fs.inotify.max_user_instances={{ max_user_instances }}'
    regexp: '^fs\.inotify\.max_user_instances={{ max_user_instances }}'
    state: present

- name: Apply sysctl
  shell: |
    sysctl --system

- name: Daemon Reload
  shell: |
    systemctl daemon-reload

- name: Configure MASQUERADE na interface ens192
  ansible.builtin.iptables:
    chain: POSTROUTING
    table: nat
    out_interface: ens192
    jump: MASQUERADE
    state: present