---
# tasks file for worker_nodes_conf
- name: Download RKE2 script
  ansible.builtin.get_url:
    url: https://get.rke2.io
    dest: /tmp/install-rke2.sh
    mode: '0100'

- name: Install RKE2
  ansible.builtin.shell: /tmp/install-rke2.sh
  environment:
    INSTALL_RKE2_TYPE: "agent"
    INSTALL_RKE2_VERSION: "{{ rke2_version }}"

- name: Enable rke2-agent.service
  ansible.builtin.shell: systemctl enable rke2-agent.service

- name: Configure Worker node
  ansible.builtin.template:
    src: config.yaml.j2
    dest: /etc/rancher/rke2/config.yaml

- name: Enable rke-agent
  ansible.builtin.shell: systemctl {{ rke2_state }} rke2-agent.service

- name: Copy kubeconfig
  ansible.builtin.copy:
    src: "rke2-kubeconfig/{{ groups['etcd'][0] }}/home/{{ ansible_user }}/rke2-kubeconfig"
    dest: "/etc/rancher/rke2"

- name: Label Worker node
  ansible.builtin.shell: /var/lib/rancher/rke2/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2-kubeconfig label nodes {{ node_name }} node-role.kubernetes.io/worker=true --overwrite=true

